name: coolasice1999/kodi-headless-cron
run-name: ${{ github.ref_name }}

on:
  workflow_dispatch:
    branches: 
        - Omega

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_info.outputs.branch }}
      tag: ${{ steps.get_info.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get info
      id: get_info

      run: |
        # Get the branch(es) that contain this tag
        git fetch --all
        branch=$(git branch -r --contains $GITHUB_SHA | grep -v HEAD | head -n1 | sed 's|origin/||' | xargs)
        echo "branch=$branch"
        echo "branch=$branch" >> $GITHUB_OUTPUT
        tag=$(git describe --tags --abbrev=0)
        echo "tag=$tag"
        echo "tag=$tag" >> $GITHUB_OUTPUT

  build_amd64:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build amd64
      uses: docker/build-push-action@v6
      with:
        context: .
        pull: true
        push: true
        platforms: linux/amd64
        tags: coolasice1999/kodi-headless-cron:${{ needs.setup.outputs.branch }}-${{ needs.setup.outputs.tag }}-amd64
